-- AlterTable
ALTER TABLE "ConnectionRequest" ADD COLUMN     "revisionInfo" TEXT,
ALTER COLUMN "orgAdminEmail" SET DATA TYPE TEXT,
ALTER COLUMN "dataDescription" SET DATA TYPE TEXT,
ALTER COLUMN "additionalInfo" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "lead" SET DATA TYPE TEXT,
ALTER COLUMN "university" SET DATA TYPE TEXT,
ALTER COLUMN "faculty" SET DATA TYPE TEXT,
ALTER COLUMN "ethicsId" SET DATA TYPE TEXT,
ALTER COLUMN "description" SET DATA TYPE TEXT;
